TeddyEcom/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    # -----------------------------------
    path('', include('pages.urls')),
    # -----------------------------------
    path('category/', include('category.urls')),
    # -----------------------------------
    path('store/', include('store.urls')),
    # -----------------------------------
    path('cart/', include('carts.urls')),
    # -----------------------------------
    path('account/', include('accounts.urls')),
    # ------------------------------------
    path('orders/', include('orders.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from carts import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),


    path('add-to-cart/<int:product_id>/',
         views.add_to_cart, name='add-to-cart'),


    path('sub-from-cart/<int:product_id>/<int:cart_item_id>',
         views.sub_from_cart, name='sub_from_cart'),


    path('remove_full_cart/<int:product_id>/<int:cart_item_id>',
         views.remove_full_cart, name='remove_full_cart'),


    path('checkout/', views.checkout, name='checkout'),
]

orders/urls.py
from django.urls import path, include
from orders import views

app_name = 'order'

urlpatterns = [
    path('place-order/', views.place_order, name='place-order'),

    # PAYMENT
    path('place-order/payments/',
         views.payments, name='payments'),

    path('place-order/payments/successful', views.successful_payments, name='successful-payments')

]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail_url'),
    path('search/', views.search, name='search'),
    
    #path for reviews
    path('submit/review/<int:product_id>', views.submit_review, name='submit-review'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    # if user is deleted, so as the cart
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    cart_quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.cart_quantity} x {self.product.product_name}'

    def sub_total(self):
        return self.product.price * self.cart_quantity

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product
from .models import Cart, CartItem
from store.models import Variation
from django.contrib.auth.decorators import login_required

# This function generates a unique cart ID based on the user's session ID


def _cart_id(req):
    cart = req.session.session_key
    if not cart:
        cart = req.session.create()
    return cart


# This function adds a product to the user's cart when the 'Add to Cart' button is clicked
def add_to_cart(req, product_id):
    current_user = req.user
    # Get the product object from the database using the product ID provided
    product = Product.objects.get(id=product_id)

    # if user is authenticated
    if current_user.is_authenticated:
        product_variation = []

        # Check if the form has been submitted using the POST method
        if req.method == 'POST':
            # Loop through all the form input elements submitted in the POST request
            for item in req.POST:
                # Get the name of the form input element that was submitted
                key = item

                # Get the selected value for the form input element
                value = req.POST[key]

                # Attempt to retrieve a Variation object with the corresponding category and value
                try:
                    variation = Variation.objects.get(
                        product=product,
                        variation_category__iexact=key,
                        variation_value__iexact=value)
                    # Append the retrieved Variation object to the product_variation list
                    product_variation.append(variation)
                except:
                    # If a Variation object with the corresponding category and value cannot be found, ignore it
                    pass

        # Check if the product is already in the cart
        does_cart_item_exist = CartItem.objects.filter(
            product=product, user=current_user).exists()

        if does_cart_item_exist:
            # If the cart item already exists, get the existing cart item and update its quantity
            cart_item = CartItem.objects.filter(
                product=product, user=current_user)
            existing_variation_list = []
            id = []

            for item in cart_item:
                # Get a list of all the variations associated with the existing cart item
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in existing_variation_list:
                # If the new product variation matches an existing cart item's variations, increase or decrease its quantity
                index = existing_variation_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.cart_quantity += 1
                item.save()
            else:
                # If the new product variation doesn't match any existing cart item's variations, update the cart item's variations
                item = CartItem.objects.create(
                    product=product, cart_quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)

                # Increment the cart item's quantity by 1 and save it
                item.save()
        else:
            # If the cart item doesn't exist, create a new one with a quantity of 1 and save it
            cart_item = CartItem.objects.create(
                product=product, cart_quantity=1, user=current_user)

            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)

            # Save the cart item
            cart_item.save()

        # Redirect the user to the 'cart' page after the product is added to the cart
        return redirect('cart:cart')

    # if user is not authenticated
    else:
        product_variation = []

        # Check if the form has been submitted using the POST method
        if req.method == 'POST':
            # Loop through all the form input elements submitted in the POST request
            for item in req.POST:
                # Get the name of the form input element that was submitted
                key = item

                # Get the selected value for the form input element
                value = req.POST[key]

                # Attempt to retrieve a Variation object with the corresponding category and value
                try:
                    variation = Variation.objects.get(
                        product=product,
                        variation_category__iexact=key,
                        variation_value__iexact=value)
                    # Append the retrieved Variation object to the product_variation list
                    product_variation.append(variation)
                except:
                    # If a Variation object with the corresponding category and value cannot be found, ignore it
                    pass

        try:
            # Try to get the cart object associated with the user's session ID
            cart = Cart.objects.get(cart_id=_cart_id(req))
        except Cart.DoesNotExist:
            # If the cart doesn't exist, create a new one with the session ID
            cart = Cart.objects.create(cart_id=_cart_id(req))

        # Save the cart object
        cart.save()

        # Check if the product is already in the cart
        does_cart_item_exist = CartItem.objects.filter(
            product=product, cart=cart).exists()

        if does_cart_item_exist:
            # If the cart item already exists, get the existing cart item and update its quantity
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            existing_variation_list = []
            id = []

            for item in cart_item:
                # Get a list of all the variations associated with the existing cart item
                existing_variation = item.variations.all()
                existing_variation_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in existing_variation_list:
                # If the new product variation matches an existing cart item's variations, increase or decrease its quantity
                index = existing_variation_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.cart_quantity += 1
                item.save()
            else:
                # If the new product variation doesn't match any existing cart item's variations, update the cart item's variations
                item = CartItem.objects.create(
                    product=product, cart_quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)

                # Increment the cart item's quantity by 1 and save it
                item.save()
        else:
            # If the cart item doesn't exist, create a new one with a quantity of 1 and save it
            cart_item = CartItem.objects.create(
                product=product, cart_quantity=1, cart=cart)

            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)

            # Save the cart item
            cart_item.save()

        # Redirect the user to the 'cart' page after the product is added to the cart
        return redirect('cart:cart')


def cart(req, total=0, quantity=0, cart_items=None):
    tax = 0
    grand_total = 0
    # Try to get the cart based on the cart id stored in the session
    try:
        if req.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=req.user, is_active=True)

        else:
            cart = Cart.objects.get(cart_id=_cart_id(req))
            # Get all the cart items for this cart that are still active
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        # Loop through all the cart items and calculate the total cost and quantity
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.cart_quantity)
            quantity += cart_item.cart_quantity

        # Calculate 8% tax similar to Cali sales tax
        tax = (8 * total)/100
        grand_total = total + tax
    # If the cart does not exist, do nothing (i.e. no items in cart)
    except Cart.DoesNotExist:
        pass

    # Create a dictionary of data to pass to the template
    context = {
        'total': total,
        'cart_quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    # Render the cart template with the context data
    return render(req, 'cart/cart.html', context)


# Function to subtract one quantity from the cart item for a given product
def sub_from_cart(req, product_id, cart_item_id):

    # Get the product that is being modified
    product = get_object_or_404(Product, id=product_id)

    try:
        if req.user.is_authenticated:
            # Get the cart item for the product in the cart
            cart_item = CartItem.objects.get(
                product=product, user=req.user, id=cart_item_id)
        else:
            # Get the cart associated with the user
            cart = Cart.objects.get(cart_id=_cart_id(req))
        # If the cart item quantity is greater than 1, subtract 1 and save the item
        if cart_item.cart_quantity > 1:
            cart_item.cart_quantity -= 1
            cart_item.save()
        else:

templates/cart/cart.html
{% extends 'base.html' %} {% block title %}Cart{% endblock title %} {% block content %} {% load static %}{% load humanize %}

<section class="section-content padding-y bg">
  <div class="container">
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
    <!--Print message -->
    <h2 class="text-center">Your Shopping Cart is Empty</h2>
    <br />
    <div class="text-center">
      <a href="{% url 'store:store' %}" class="btn btn-primary">
        Continue Shopping
      </a>
    </div>
    {% else %}
    <div class="row">
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              {% for cart_item in cart_items %}
              <tr>
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside">
                      <img
                        src="{{ cart_item.product.images.url }}"
                        class="img-sm"
                      />
                    </div>
                    <figcaption class="info">
                      <a
                        href="{{ cart_item.product.get_url }}"
                        class="title text-dark"
                        >{{ cart_item.product.product_name }}</a
                      >
                      <p class="text-muted small">
                        {% if cart_item.variations.all %} {% for item in cart_item.variations.all %}
                         {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }}
                        <br />
                        {% endfor %} {% endif %}
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <a
                          href="{% url 'cart:sub_from_cart' cart_item.product.id cart_item.id %}"
                          class="btn btn-light"
                          type="button"
                          id="button-plus"
                        >
                          <i class="fa fa-minus"></i>
                        </a>
                      </div>
                      <input
                        type="text"
                        class="form-control"
                        value="{{ cart_item.cart_quantity }}"
                      />
                      <div class="input-group-append">
                        <form
                          action="{% url 'cart:add-to-cart' cart_item.product.id %}"
                          method="POST"
                        >
                          {% csrf_token %} {% for item in cart_item.variations.all %}
                          <input
                            type="hidden"
                            name="{{ item.variation_category | lower }}"
                            value="{{ item.variation_value | capfirst }}"
                          />
                          {% endfor %}
                          <button
                            class="btn btn-light"
                            type="submit"
                            id="button-minus"
                          >
                            <i class="fa fa-plus"></i>
                          </button>
                        </form>
                      </div>
                    </div>
                    <!-- input-group.// -->
                  </div>
                  <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">$ {{ cart_item.sub_total | intcomma }}</var>
                    <small class="text-muted">
                      $ {{ cart_item.product.price |intcomma}} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a
                    href="{% url 'cart:remove_full_cart' cart_item.product.id cart_item.id %}"
                    onclick="return confirm('Are you sure you want to delete this item?')"
                    class="btn btn-danger"
                  >
                    Remove</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <aside class="col-lg-3">
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total price:</dt>
              {% if total == 0 %}
              <dd class="text-right">$0</dd>
              {% else %}
              <dd class="text-right">${{total | intcomma}}</dd>
              {% endif %}
            </dl>
            <dl class="dlist-align">
              <dt>Tax:</dt>
              {% if tax == 0 %}
              <dd class="text-right">$0</dd>
              {% else %}
              <dd class="text-right">${{tax | intcomma}}</dd>
              {% endif %}
            </dl>
            <dl class="dlist-align">
              <dt>Total:</dt>
              {% if grand_total == 0 %}
              <dd class="text-right text-dark b">
                <strong>$0</strong>
              </dd>
              {% else %}
              <dd class="text-right text-dark b">
                <strong>${{grand_total | intcomma}}</strong>
              </dd>
              {% endif %}
            </dl>
            <hr />
            <p class="text-center mb-3">
              <img src="{% static 'images/misc/payments.png' %}" height="26" />
            </p>
            <a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block">
              Checkout
            </a>
            <a href="{% url 'store:store' %}" class="btn btn-light btn-block"
              >Continue Shopping</a
            >
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
    </div>
    <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/cart/checkout.html
{% extends 'base.html' %} {% block title %}Checkout{% endblock title %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->

<div class="row">
	<aside class="col-lg-6">
<div class="card">
  <div class="card-body">
    <h4 class="card-title mb-4">Billing Address</h4>
    <form action="{% url 'order:place-order' %}" method="POST">
      {% csrf_token %}
      <div class="form-row">
        <div class="col form-group">
          <label for="">First Name</label>
          <input type="text" name="first_name" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Last Name</label>
          <input type="text" name="last_name" class="form-control" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <label for="">Email</label>
          <input type="email" name="email" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Phone Number</label>
          <input type="text" name="phone_number" class="form-control" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <label for="">Address Line 1</label>
          <input type="text" name="address_line_1" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Address Line 2</label>
          <input type="text" name="address_line_2" class="form-control">
        </div>
      </div>
      <div class="form-row">
        <div class="col form-group">
          <label for="">City</label>
          <input type="text" name="city" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">State</label>
          <input type="text" name="state" class="form-control" required>
        </div>
        <div class="col form-group">
          <label for="">Country</label>
          <input type="text" name="country" class="form-control" required>
        </div>
        </div>
        <div class="form-row">
          <label for="">Order Note</label>
          <textarea name="order_note" rows="2" class="form-control"></textarea>
        </div>
 

  </div>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-6">

		<div class="card">
		<div class="card-body">
      <table class="table table-borderless table-shopping-cart">
      <thead class="text-muted">
      <tr class="small text-uppercase">
        <th scope="col">Product</th>
        <th scope="col" width="120">Quantity</th>
        <th scope="col" width="120">Price</th>

      </tr>
      </thead>
      <tbody>

      {% for cart_item in cart_items %}
      <tr>
      	<td>
      		<figure class="itemside align-items-center">
      			<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
      			<figcaption class="info">
      				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
      				<p class="text-muted small">
      					{% if cart_item.variations.all %}
      						{% for item in cart_item.variations.all %}
      							{{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
      						{% endfor %}
      					{% endif %}
      				</p>
      			</figcaption>
      		</figure>
      	</td>
      	<td>
      		<!-- col.// -->
      				<label for="">{{cart_item.cart_quantity}}</label>
      	</td>
      	<td>
      		<div class="price-wrap">
      			<var class="price">$ {{ cart_item.sub_total }}</var>
      			<small class="text-muted"> $ {{ cart_item.product.price }} each </small>
      		</div> <!-- price-wrap .// -->
      	</td>

      </tr>
      {% endfor %}

      </tbody>
      </table>
          <button type="submit" name="submit" class="btn btn-primary btn-block">Place Order</button>
			    <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
      </form>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->


</aside> <!-- col.// -->


</div> <!-- row.// -->

<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}