TeddyEcom/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    # -----------------------------------
    path('', include('pages.urls')),
    # -----------------------------------
    path('category/', include('category.urls')),
    # -----------------------------------
    path('store/', include('store.urls')),
    # -----------------------------------
    path('cart/', include('carts.urls')),
    # -----------------------------------
    path('account/', include('accounts.urls')),
    # ------------------------------------
    path('orders/', include('orders.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'users'

urlpatterns = [
    path('register-user/', views.register_user, name='register-user'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    
    path('login-user/', views.login_user, name='login-user'),
    path('logout-user/', views.logout_user, name='logout-user'),
    
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    
    path('forgot-password/', views.forgotPassword, name='forgot-password'),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset-password-page/', views.reset_password_page, name='reset-password-page')

    
]

carts/urls.py
from django.urls import path
from carts import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),


    path('add-to-cart/<int:product_id>/',
         views.add_to_cart, name='add-to-cart'),


    path('sub-from-cart/<int:product_id>/<int:cart_item_id>',
         views.sub_from_cart, name='sub_from_cart'),


    path('remove_full_cart/<int:product_id>/<int:cart_item_id>',
         views.remove_full_cart, name='remove_full_cart'),


    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail_url'),
    path('search/', views.search, name='search'),
    
    #path for reviews
    path('submit/review/<int:product_id>', views.submit_review, name='submit-review'),
]

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account


class Product(models.Model):

    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField(blank=False)
    is_avalible = models.BooleanField(default=True)

    # models.CASCADE will delete all products attached to a category if that category is deleted
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        # this time we take 2 arguments because in our link, we have 2 slugs necessary
        return reverse('store:product_detail_url', args=[self.category.slug, self.slug])


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def materials(self):
        return super(VariationManager, self).filter(variation_category='material', is_active=True)


class Variation(models.Model):
    variation_category_choice = (
        ('material', 'material'),
        ('color', 'color')
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(
        max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.IntegerField()
    ip_address = models.CharField(max_length=20, blank=True)

    # if admin wants to disable the review, they have an option for it
    status = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = [
            'subject',
            'review',
            'rating',
        ]

store/views.py
from django.shortcuts import render, get_object_or_404, redirect

from orders.models import OrderProduct
from .models import Product, ReviewRating
from django.contrib import messages
from category.models import Category
from carts.models import CartItem
from django.core.paginator import Paginator
from carts.views import _cart_id
from django.db.models import Q
from .forms import ReviewForm


def store(req, category_slug=None):
    categories = None
    products = None

    # If a category slug is specified, get the Category object for that slug
    if category_slug != None:
        categories = get_object_or_404(
            Category, slug=category_slug)

        # Get all products that belong to the specified category and are available
        products = Product.objects.filter(
            category=categories, is_avalible=True).order_by('id')
        # order-by here will remove the error that compiler tells about there's no order

        # Pagination
        paginator = Paginator(products, 3)
        page = req.GET.get('page')
        paged_products = paginator.get_page(page)

        # Count the number of products in the category
        product_count = products.count()

    # If no category slug is specified, get all products that are available
    else:
        products = Product.objects.order_by(
            '-created_date').filter(is_avalible=True)

        paginator = Paginator(products, 6)
        page = req.GET.get('page')

        paged_products = paginator.get_page(page)

        # Count the number of products
        product_count = products.count()

    # Create a dictionary of variables to be used in the template
    context = {
        'Category': categories,
        'Product': paged_products,
        'product_count': product_count,
    }

    # Render the template with the dictionary of variables
    return render(req, 'pages/store.html', context)


def product_detail(req, category_slug, product_slug):
    try:
        # Get the single Product object that matches the specified category and product slugs
        single_product = Product.objects.get(
            category__slug=category_slug, slug=product_slug)

        # Check if the product is already in the user's cart
        in_cart = CartItem.objects.filter(
            cart__cart_id=_cart_id(req), product=single_product).exists()

    except Exception as e:
        raise e

    if req.user.is_authenticated:
        try:
            ordered_product = OrderProduct.objects.filter(
                user=req.user, product_id=single_product.id).exists()

        except OrderProduct.DoesNotExist:
            ordered_product = None
    else:
        ordered_product = None

    # Get all the reviews
    # When admin doesnt want to show a particular reivew, they can turn status False to make reivew dissapear
    reviews = ReviewRating.objects.filter(
        product_id=single_product.id, status=True)

    # Create a dictionary of variables to be used in the template
    context = {
        'product': single_product,
        'in_cart': in_cart,  # Add the in_cart variable to the context dictionary,
        'ordered_product': ordered_product,
        'reviews': reviews
    }

    # Render the template with the dictionary of variables
    return render(req, 'pages/productPage.html', context)

# The in_cart variable checks whether the product is already in the user's
# cart or not. It does this by using the CartItem.objects.filter() method to
# look for a CartItem object that has a cart attribute with the same cart_id as the user's current
# cart (as obtained by calling _cart_id(req)), and a product attribute that matches the single_product
# object that we just obtained.

# The exists() method is then called on the resulting queryset to return a boolean
# value indicating whether such a CartItem object exists or not. If it exists, that
# means the product is already in the user's cart, and in_cart is set to True. Otherwise, in_cart
# is set to False. This in_cart variable is then added to the context dictionary and
# passed to the productPage.html template for use in the template.


# SEARCH BASED ON PROUDCT DESCRIPTION
def search(req):
    if 'keyword' in req.GET:
        # Retrieve the search keyword from the query string
        keyword = req.GET['keyword']

        if keyword:
            # Filter the Product objects based on the search keyword
            # Use the `Q` object to make a complex query with multiple filters
            # The `icontains` lookup retrieves objects where the description field contains the keyword, case-insensitive
            # The `iexact` lookup retrieves objects where the product_name field matches the keyword exactly, case-insensitive
            products = Product.objects.order_by('-created_date').filter(
                Q(description__icontains=keyword) | Q(product_name__iexact=keyword))
            # Get the count of products that match the search keyword
            product_count = products.count()

        # Print the search keyword to the console
        print(keyword)

    # Create a dictionary of variables to be used in the template
    context = {
        'Product': products,  # Add the products variable to the context dictionary
        'product_count': product_count
    }

    # Render the template with the dictionary of variables
    return render(req, 'pages/store.html', context)


def submit_review(req, product_id):
    url = req.META.get('HTTP_REFERER')  # store the already existing URL
    if req.method == 'POST':
        try:
            review = ReviewRating.objects.get(
                user__id=req.user.id, product__id=product_id)
            form = ReviewForm(req.POST, instance=review)

            if form.is_valid():
                form.save()  # Save the updated form

                messages.success(
                    req, 'Thank you. Your review has been updated')
            else:
                messages.error(req, 'Failed to update the review')

            return redirect(url)

        except ReviewRating.DoesNotExist:
            form = ReviewForm(req.POST)

            if form.is_valid():
                data = form.save(commit=False)
                data.ip_address = req.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = req.user.id
                data.save()

                messages.success(
                    req, 'Thank you. Your review has been submitted')
            else:
                messages.error(req, 'Failed to submit the review')

            return redirect(url)

templates/pages/dashboard.html
{% extends 'base.html' %} {% block title %}dashboard{% endblock title %} 
{% block content %}{% load static %}

<section class="section-conten padding-y bg">
  {% include 'shared/messages.html' %}
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <!--   SIDEBAR   -->
        <ul class="list-group">
          <a class="list-group-item active" href="#"> My order history </a>
          <a class="list-group-item" href="#"> Transactions </a>
          <a class="list-group-item" href="#"> Return and refunds </a>
          <a class="list-group-item" href="#">Settings </a>
          <a class="list-group-item" href="#"> My Selling Items </a>
          <a class="list-group-item" href="#"> Received orders </a>
        </ul>
        <br />
        <a class="btn btn-light btn-block" href="{% url 'users:logout-user' %}">
          <i class="fa fa-power-off"></i> <span class="text">Log out</span>
        </a>
        <!--   SIDEBAR .//END   -->
      </aside>
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
            <span>Order Date: 16 December 2018</span>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="text-muted">Delivery to</h6>
                <p>
                  Michael Jackson <br />
                  Phone +1234567890 Email: myname@pixsellz.com <br />
                  Location: Home number, Building name, Street 123, Tashkent,
                  UZB <br />
                  P.O. Box: 100123
                </p>
              </div>
              <div class="col-md-4">
                <h6 class="text-muted">Payment</h6>
                <span class="text-success">
                  <i class="fab fa-lg fa-cc-visa"></i>
                  Visa **** 4216
                </span>
                <p>
                  Subtotal: $356 <br />
                  Shipping fee: $56 <br />
                  <span class="b">Total: $456 </span>
                </p>
              </div>
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
          <div class="table-responsive">
            <table class="table table-hover">
              <tr>
                <td width="65">
                  <img src="../images/items/1.jpg" class="img-xs border" />
                </td>
                <td>
                  <p class="title mb-0">Product name goes here</p>
                  <var class="price text-muted">USD 145</var>
                </td>
                <td>
                  Seller <br />
                  Nike clothing
                </td>
                <td width="250">
                  <a href="#" class="btn btn-outline-primary">Track order</a>
                  <a href="#" class="btn btn-light"> Details </a>
                </td>
              </tr>
              <tr>
                <td>
                  <img src="../images/items/2.jpg" class="img-xs border" />
                </td>
                <td>
                  <p class="title mb-0">Another name goes here</p>
                  <var class="price text-muted">USD 15</var>
                </td>
                <td>
                  Seller <br />
                  ABC shop
                </td>
                <td>
                  <a href="#" class="btn btn-outline-primary">Track order</a>
                  <a href="#" class="btn btn-light"> Details </a>
                </td>
              </tr>
              <tr>
                <td>
                  <img src="../images/items/3.jpg" class="img-xs border" />
                </td>
                <td>
                  <p class="title mb-0">The name of the product goes here</p>
                  <var class="price text-muted">USD 145</var>
                </td>
                <td>
                  Seller <br />
                  Wallmart
                </td>
                <td>
                  <a href="#" class="btn btn-outline-primary">Track order</a>
                  <a href="#" class="btn btn-light"> Details </a>
                </td>
              </tr>
            </table>
          </div>
          <!-- table-responsive .end// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>

  {% endblock content %}
</section>

templates/pages/home.html
{% extends 'base.html' %} {% block title %}TeddyEcom{% endblock %} 
{% block content %} {% load static %} {% load humanize %}
<section class="section-intro padding-y-sm">
  <div class="container">
    <div class="intro-banner-wrap">
      <img
        src="{% static 'images/banners/Banner.webp' %}"
        class="img-fluid rounded"
      />
    </div>
  </div>
  <!-- container //  -->
</section>

<section class="section-name padding-y-sm">
  <div class="container">
    <header class="section-heading">
      <a href="{% url 'store:store' %}" class="btn btn-outline-primary float-right"
        >See all</a
      >
      <h3 class="section-title">Popular products</h3>
    </header>
    <!-- sect-heading -->

    <div class="row">
      {% for product in Product %}
      <div class="col-md-3">
        <div class="card card-product-grid">
          <a href="{{product.get_url}}" class="img-wrap">
            <img src="{{product.images.url}}" />
          </a>
          <figcaption class="info-wrap">
            <a href="{{product.get_url}}" class="title"
              >{{product.product_name}}</a
            >
            <div class="price mt-1">${{product.price | intcomma}}</div>
            <!-- price-wrap.// -->
          </figcaption>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- row.// -->
  </div>
  <!-- container // -->
</section>
{% endblock %}

templates/pages/productPage.html
{% extends 'base.html' %} {% block title %}Product{% endblock %} 
{% block content %} {% load static %} {% load humanize %}


<section class="section-content padding-y bg">
  <div class="container">
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap">
              <a href="#"><img src="{{product.images.url}}" /></a>
            </div>
            <!-- img-big-wrap.// -->
          </article>
          <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'cart:add-to-cart' product_id=product.id %}" method="POST">
            {% csrf_token %}
          <article class="content-body">
            <h2 class="title">{{product.product_name}}</h2>

            <div class="mb-3">
              <var class="price h4">${{product.price | intcomma}}</var>
            </div>

            <p>{{product.description}}</p>

            <hr />
            <!-- row.// -->
              
            <div class="row">
              {% if product.variation_set.colors %}
                <label for="color">Strap Color:</label>
                  <select class="form-control" id="color" name="color" required>
                      <option value="" disabled selected>Choose Color</option>
                      {% for st in product.variation_set.colors %}
                          <option value="{{st.variation_value}}">{{st.variation_value|capfirst}}</option>
                      {% endfor %}
                  </select>
              {% else %}
                  <p>No color variations available.</p>
                  <hr />
              {% endif %}
          </div>
          <div class="row">
              {% if product.variation_set.materials %}
                <label for="material">Strap Material:</label>
                  <select class="form-control" id="material" name="material">
                      <option value="" disabled selected>Choose Material</option>
                      {% for st in product.variation_set.materials %}
                          <option value="{{st.variation_value}}">{{st.variation_value|capfirst}}</option>
                      {% endfor %}
                  </select>
              {% else %}
                  <p>No material variations available.</p>
                  <hr />
              {% endif %}
          </div>
          
          
            <!-- row.// -->
            <hr />
            {% if product.stock <= 0 %}
            <h5 class="text-danger">Out of Stock</h5>
            {% else %} 
            <button
              type="submit"
              class="btn btn-primary"
            >
              <span class="text">Add to cart</span>
              <i class="fas fa-shopping-cart"></i>
            </button>
          </form>
            {% endif %}
          </article>
          <!-- product-info-aside .// -->
        </main>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br />

    <div class="row">
      <div class="col-md-9">
        <header class="section-heading">
          <h3>Customer Reviews</h3>
          {% include 'shared/messages.html' %}
        </header>

        <form action="{% url 'store:submit-review' product.id %}" method="POST">
          {% csrf_token %}
        
          <h5>Write your Review</h5>
          <div>
            <!-- Rating stars -->
            <fieldset class="rating">
              <input type="radio" id="star5" name="rating" value="5" required>
              <label for="star5" title="5 stars"></label>
              <input type="radio" id="star4" name="rating" value="4" required>
              <label for="star4" title="4 stars"></label>
              <input type="radio" id="star3" name="rating" value="3" required>
              <label for="star3" title="3 stars"></label>
              <input type="radio" id="star2" name="rating" value="2" required>
              <label for="star2" title="2 stars"></label>
              <input type="radio" id="star1" name="rating" value="1" required>
              <label for="star1" title="1 star"></label>
            </fieldset>
        
            Review Title: 
            <input type="text" class="form-control" name="subject">
            <br />
        
            Text Area:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br />
        
            {% if user.is_authenticated %}
              {% if ordered_product %}
                <input type="submit" value="Submit Review" class="btn btn-primary">
              {% else %}
              <p>Must purchase {{product.product_name}} first before reviewing it</p>
              {% endif %}
            {% else %}
              <p>Must be logged in to post a reivew. <span><a href="{% url 'users:login-user' %}">Login Now</a></span></p>
            {% endif %}
            
          </div>
        </form>
        
        

        <br />
        <article class="box mb-3">
          {% for review in reviews %}
          <div class="icontext w-100">
            <div class="text">
              <span class="date text-muted float-md-right">{{review.updated_at}} </span>
              <h6 class="mb-1">{{ review.user.full_name }}</h6>
              <div>
                {% for i in "12345" %}
                  {% if forloop.counter <= review.rating %}
                    <i class="fa fa-star" style="color: #f8d64e;"></i>
                  {% else %}
                    <i class="far fa-star" style="color: #f8d64e;"></i>
                  {% endif %}
                {% endfor %}
              </div>              
            </div>
          </div>
          <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{review.subject}}</h6>
            <p>
              {{review.review}}
            </p>
          </div>
          {% endfor %}
          
        </article>
      </div>
      <!-- col.// -->
    </div>
    <!-- row.// -->
  </div>
  <!-- container .//  -->
</section>

{% endblock content %}

templates/pages/store.html
{% extends 'base.html' %} {% block title %}Store{% endblock %} 
{% block content %} {% load static %} {% load humanize %}

<section class="section-pagetop bg">
  <div class="container">
    {% if 'search' in request.path %}
      <h2 class="title-page">Search Result</h2>
    {% else %}
    <h2 class="title-page">Our Store</h2>
    {% endif %}
    
  </div>
  <!-- container //  -->
</section>

<section class="section-content padding-y">
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <div class="card">
          <article class="filter-group">
            <header class="card-header">
              <a
                href="#"
                data-toggle="collapse"
                data-target="#collapse_1"
                aria-expanded="true"
                class=""
              >
                <i class="icon-control fa fa-chevron-down"></i>
                <h6 class="title">Categories</h6>
              </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
              <div class="card-body">
                <ul class="list-menu">
                  <a class="dropdown-item" href="{% url 'store:store' %}"
                    >All Products</a
                  >
                  {% for category in links %}
                  <a class="dropdown-item" href="{{ category.get_url }}"
                    >{{ category.category_name }}</a
                  >
                  {% endfor %}
                </ul>
              </div>
              <!-- card-body.// -->
            </div>
          </article>
          <!-- filter-group  .// -->

          <article class="filter-group">
            <header class="card-header">
              <a
                href="#"
                data-toggle="collapse"
                data-target="#collapse_3"
                aria-expanded="true"
                class=""
              >
                <i class="icon-control fa fa-chevron-down"></i>
                <h6 class="title">Price range</h6>
              </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
              <div class="card-body">
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label>Min</label>
                    <!-- <input class="form-control" placeholder="$0" type="number"> -->
                    <select class="mr-2 form-control">
                      <option value="0">$5000</option>
                      <option value="50">$7000</option>
                      <option value="100">$10000</option>
                      <option value="150">$150</option>
                      <option value="200">$200</option>
                      <option value="500">$500</option>
                      <option value="1000">$1000</option>
                    </select>
                  </div>
                  <div class="form-group text-right col-md-6">
                    <label>Max</label>
                    <select class="mr-2 form-control">
                      <option value="50">$50</option>
                      <option value="100">$100</option>
                      <option value="150">$150</option>
                      <option value="200">$200</option>
                      <option value="500">$500</option>
                      <option value="1000">$1000</option>
                      <option value="2000">$2000+</option>
                    </select>
                  </div>
                </div>
                <!-- form-row.// -->
                <button class="btn btn-block btn-primary">Apply</button>
              </div>
              <!-- card-body.// -->
            </div>
          </article>
          <!-- filter-group .// -->
        </div>
        <!-- card.// -->
      </aside>
      <!-- col.// -->
      <main class="col-md-9">
        <header class="border-bottom mb-4 pb-3">
          <div class="form-inline">
            <span class="mr-md-auto">Found <b>{{product_count}}</b> items</span>
          </div>
        </header>
        <!-- sect-heading -->

        <div class="row">
          {% for product in Product %}
          <div class="col-md-4">
            <figure class="card card-product-grid">
              <div class="img-wrap">
                <img src="{{product.images.url}}" />
              </div>
              <!-- img-wrap.// -->
              <figcaption class="info-wrap">
                <div class="fix-height">
                  <a href="{{product.get_url}}" class="title"
                    >{{product.product_name}}</a
                  >
                  <div class="price-wrap mt-2">
                    <span class="price">${{product.price | intcomma}}</span>
                    <del class="price-old">$1980</del>
                  </div>
                </div>
                {% if product.stock <= 0 %}
                <h5 class="btn btn-danger">Out of Stock</h5>
                {% else %}
                <a href="{{product.get_url}}" class="btn btn-primary">
                  <span class="text">View Product</span>
                  <i class="fas fa-eye"></i>
                </a>
                {% endif %}
              </figcaption>
            </figure>
          </div>
          {% endfor %}
        </div>
        <!-- row end.// -->

        <nav class="mt-4" aria-label="Page navigation sample">
          {% if Product.has_other_pages %}
          <ul class="pagination">
            {% if Product.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{Product.previous_page_number}}">Previous</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}

            {% for product in Product.paginator.page_range %}
              {% if Product.number == product %}
                <li class="page-item active"><a class="page-link" href="#">{{product}}</a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{product}}">{{product}}</a></li>
              {% endif %}
            {% endfor %}

            {% if Product.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{Product.next_page_number}}">Next</a></li>
            {% else %}
              <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </main>
      <!-- col.// -->
    </div>
  </div>
  <!-- container .//  -->
</section>
{% endblock %}