TeddyEcom/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    # -----------------------------------
    path('', include('pages.urls')),
    # -----------------------------------
    path('category/', include('category.urls')),
    # -----------------------------------
    path('store/', include('store.urls')),
    # -----------------------------------
    path('cart/', include('carts.urls')),
    # -----------------------------------
    path('account/', include('accounts.urls')),
    # ------------------------------------
    path('orders/', include('orders.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'users'

urlpatterns = [
    path('register-user/', views.register_user, name='register-user'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    
    path('login-user/', views.login_user, name='login-user'),
    path('logout-user/', views.logout_user, name='logout-user'),
    
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    
    path('forgot-password/', views.forgotPassword, name='forgot-password'),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset-password-page/', views.reset_password_page, name='reset-password-page')

    
]

carts/urls.py
from django.urls import path
from carts import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),


    path('add-to-cart/<int:product_id>/',
         views.add_to_cart, name='add-to-cart'),


    path('sub-from-cart/<int:product_id>/<int:cart_item_id>',
         views.sub_from_cart, name='sub_from_cart'),


    path('remove_full_cart/<int:product_id>/<int:cart_item_id>',
         views.remove_full_cart, name='remove_full_cart'),


    path('checkout/', views.checkout, name='checkout'),
]

pages/urls.py
from django.urls import path
from pages import views

app_name = "pages"


urlpatterns = [
    path('', views.home, name='home'),
]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail_url'),
    path('search/', views.search, name='search'),
    
    #path for reviews
    path('submit/review/<int:product_id>', views.submit_review, name='submit-review'),
]

templates/shared/footer.html
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div>
</footer>

templates/shared/header.html
{% load static %}
<header class="section-header">
  <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarTop4"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link"> English </a>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link"> USD </a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li>
            <a href="#" class="nav-link">
              <i class="fa fa-envelope"></i> Email
            </a>
          </li>
          <li>
            <a href="#" class="nav-link">
              <i class="fa fa-phone"></i> Call us
            </a>
          </li>
        </ul>
        <!-- list-inline //  -->
      </div>
      <!-- navbar-collapse .// -->
    </div>
    <!-- container //  -->
  </nav>

  <section class="header-main border-bottom">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
          <a href="{% url 'pages:home' %}" class="brand-wrap">
            <img class="logo" src="{% static 'images/logo.png' %}" />
          </a>
          <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
          <div class="category-wrap dropdown d-inline-block float-right">
            <button
              type="button"
              class="btn btn-primary dropdown-toggle"
              data-toggle="dropdown"
            >
              <i class="fa fa-bars"></i> All category
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'store:store' %}"
                >All Products</a
              >
              {% for category in links %}
              <a class="dropdown-item" href="{{ category.get_url }}"
                >{{ category.category_name }}</a
              >
              {% endfor %}
            </div>
          </div>
          <!-- category-wrap.// -->
        </div>
        <!-- col.// -->
        <a href="{% url 'store:store' %}" class="btn btn-outline-primary"
          >Store</a
        >
        <div class="col-lg col-md-6 col-sm-12 col">
          <form action="{% url 'store:search' %}" class="search" method="GET">
            <div class="input-group w-100">
              <input
                type="text"
                class="form-control"
                style="width: 60%"
                placeholder="Search Keyword: Rolex, Hublot, etc.."
                name="keyword"
              />
              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </div>
          </form>
          <!-- search-wrap .end// -->
        </div>
        <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
          <div class="d-flex justify-content-end mb-3 mb-lg-0">
            {% if user.id is None%}
            <div class="widget-header">
              <small class="title text-muted">Welcome guest!</small>
              <div>
                <a href="{% url 'users:login-user' %}">Sign in</a>
                <span class="dark-transp"> | </span>
                <a href="{% url 'users:register-user' %}"> Register</a>
              </div>
            </div>
            <a href="{% url 'cart:cart' %}" class="widget-header pl-3 ml-3">
              <div class="icon icon-sm rounded-circle border">
                <i class="fa fa-shopping-cart"></i>
              </div>
            {%else%}
            <div class="widget-header">
              <small class="title text-muted">Welcome {{user.first_name}}!</small>
              <div>
                <a href="{% url 'users:logout-user' %}">Sign Out</a>
                <span class="dark-transp"> | </span>
                <a href="{% url 'users:dashboard' %}"> Dashboard</a>
              </div>
            </div>
            <a href="{% url 'cart:cart' %}" class="widget-header pl-3 ml-3">
              <div class="icon icon-sm rounded-circle border">
                <i class="fa fa-shopping-cart"></i>
              </div>
            {%endif%} 
              <span class="badge badge-pill badge-danger notify">{{counter}}</span>
            </a>
          </div>
          <!-- widgets-wrap.// -->
        </div>
        <!-- col.// -->
      </div>
      <!-- row.// -->
    </div>
    <!-- container.// -->
  </section>
  <!-- header-main .// -->
</header>
<!-- section-header.// -->

templates/shared/messages.html
{% if messages%} 
    {% for message in messages %}
        <div id="message-for-forms" class="container">
        <div class="alert alert-{{ message.tags }}" alert-dismissible role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="True">&times;</span>
            </button>

            <strong>
            {%if message.level == DEFAULT_MESSAGE.ERROR%} Error: {% else %}
            {{message.tags|title}} {%endif %}
            </strong>
            {{ message }}
        </div>
        </div>
    {% endfor %} 
{% endif %}