TeddyEcom/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()
admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),
    # -----------------------------------
    path('', include('pages.urls')),
    # -----------------------------------
    path('category/', include('category.urls')),
    # -----------------------------------
    path('store/', include('store.urls')),
    # -----------------------------------
    path('cart/', include('carts.urls')),
    # -----------------------------------
    path('account/', include('accounts.urls')),
    # ------------------------------------
    path('orders/', include('orders.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'users'

urlpatterns = [
    path('register-user/', views.register_user, name='register-user'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    
    path('login-user/', views.login_user, name='login-user'),
    path('logout-user/', views.logout_user, name='logout-user'),
    
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    
    path('forgot-password/', views.forgotPassword, name='forgot-password'),
    path('reset-password-validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset-password-page/', views.reset_password_page, name='reset-password-page')

    
]

carts/urls.py
from django.urls import path
from carts import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),


    path('add-to-cart/<int:product_id>/',
         views.add_to_cart, name='add-to-cart'),


    path('sub-from-cart/<int:product_id>/<int:cart_item_id>',
         views.sub_from_cart, name='sub_from_cart'),


    path('remove_full_cart/<int:product_id>/<int:cart_item_id>',
         views.remove_full_cart, name='remove_full_cart'),


    path('checkout/', views.checkout, name='checkout'),
]

templates/users/forgotPassword.html
{% extends 'base.html' %} {% block title %}Forgot Password{% endblock title %} 
{% block content %}{% load static %}

<section class="section-conten padding-y" style="min-height: 84vh">
  <div class="card mx-auto" style="max-width: 380px; margin-top: 100px">
    {% include 'shared/messages.html' %}
    <div class="card-body">
      <h4 class="card-title mb-4">Forgot Password</h4>
      <p>Type the email associated with your account</p>
      <form action="{% url 'users:forgot-password' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input
            type="email"
            class="form-control"
            name='email'
            placeholder="Email Address..."
          />
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Recover Password</button>
        </div>
      </form>
    </div>
  </div>
  <p class="text-center mt-4">Remember Your Password? <a href="{% url 'users:login-user' %}">Sign in</a></p>
  <br /><br />
</section>
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %} {% block title %}Login page{% endblock title %} 
{% block content %}{% load static %}

<section class="section-conten padding-y" style="min-height: 84vh">
  <div class="card mx-auto" style="max-width: 380px; margin-top: 100px">
    {% include 'shared/messages.html' %}
    <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      <form action="{% url 'users:login-user' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <input
            type="email"
            class="form-control"
            name='email'
            placeholder="Email Address"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Password" name='password'/>
        </div>
        <!-- form-group// -->

        <div class="form-group">
          <a href="{% url 'users:forgot-password' %}" class="float-right">Forgot password?</a>
        </div>
        <!-- form-group form-check .// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">Login</button>
        </div>
        <!-- form-group// -->
      </form>
    </div>
    <!-- card-body.// -->
  </div>
  <!-- card .// -->

  <p class="text-center mt-4">Don't have account? <a href="{% url 'users:register-user' %}">Sign up</a></p>
  <br /><br />
</section>
{% endblock content %}

templates/users/registration.html
{% extends 'base.html' %} {% block title %}Registration page{% endblock title %}
{% block content %}{% load static %}

<section class="section-content padding-y">
  <div class="card mx-auto" style="max-width: 520px; margin-top: 40px">
    <article class="card-body">
      {% include 'shared/messages.html' %}
      <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
      <form action="{% url 'users:register-user' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="col form-group col-md-6">
            <label>First name</label>
            {{form.first_name}}
          </div>
          <!-- form-group end.// -->
          <div class="col form-group col-md-6">
            <label>Last name</label>
            {{form.last_name}}
          </div>
          <div class="col form-group col-md-6">
            <label>Email</label>
            {{form.email}}
          </div>
          <div class="col form-group col-md-6">
            <label>Phone Number</label>
            {{form.phone_number}}
          </div>
          <div class="col form-group col-md-6">
            <label>Password</label>
            {{form.password}}
          </div>
          <div class="col form-group col-md-6">
            <label>Confirm Password</label>
            {{form.confirm_password}}
          </div>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Register
          </button>
        </div>
      </form>
    </article>
    <!-- card-body.// -->
  </div>
  <!-- card .// -->
  <p class="text-center mt-4">
    Have an account? <a href="{% url 'users:login-user' %}">Log In</a>
  </p>
  <br /><br />
</section>
{% endblock content %}

templates/users/resetPassword.html
{% extends 'base.html' %}{% block title %}Reset Password{% endblock title %} 
{% block content %} {% load static %}{% load humanize %} 

<section class="section-conten padding-y" style="min-height: 84vh">
    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px">
      {% include 'shared/messages.html' %}
      <div class="card-body">
        <h4 class="card-title mb-4">Reset Password</h4>
        <p>Create your new password</p>
        <form action="{% url 'users:reset-password-page' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <input
              type="password"
              class="form-control"
              name='password'
              placeholder="Enter new password..."
            />
          </div>
          <div class="form-group">
            <input
              type="password"
              class="form-control"
              name='confirm_password'
              placeholder="Confirm Password..."
            />
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Create New Password</button>
          </div>
        </form>
      </div>
    </div>
    <br /><br />
  </section>



{% endblock content %}